// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvMxY6qC8YyXQz1HAKA5qDouCNn9bhIg',
    appId: '1:66531588201:web:21a3af88b525a095658af8',
    messagingSenderId: '66531588201',
    projectId: 'finalprojectmad-48331',
    authDomain: 'finalprojectmad-48331.firebaseapp.com',
    storageBucket: 'finalprojectmad-48331.appspot.com',
    measurementId: 'G-Y0X0RNHW1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bjdhjExJeE9R8xzTnWp9VgTQ5IBF2cc',
    appId: '1:66531588201:android:a899edc7acc3e6a9658af8',
    messagingSenderId: '66531588201',
    projectId: 'finalprojectmad-48331',
    storageBucket: 'finalprojectmad-48331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtptHX_SA9mWjqux-OYtJBNE1m1li0dGM',
    appId: '1:66531588201:ios:9e04d40dbf171b82658af8',
    messagingSenderId: '66531588201',
    projectId: 'finalprojectmad-48331',
    storageBucket: 'finalprojectmad-48331.appspot.com',
    iosBundleId: 'com.example.finalprojexct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtptHX_SA9mWjqux-OYtJBNE1m1li0dGM',
    appId: '1:66531588201:ios:ad87dc28b1ad575d658af8',
    messagingSenderId: '66531588201',
    projectId: 'finalprojectmad-48331',
    storageBucket: 'finalprojectmad-48331.appspot.com',
    iosBundleId: 'com.example.finalprojexct.RunnerTests',
  );
}
